server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /
    
spring: 
    application:
      name: spring_cloud
   
org:
  zoo:
    swan:
      started: false
      token-support: SnowId
      swan-redis-config:
        host-name: 127.0.0.1
        port: 6379
        password: 


logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: info
        org.zoo.cat.bonuspoint: debug
        org.zoo.cat.lottery: debug
        org.zoo.cat: debug
        io.netty: info
    path: "./logs"

